word = input('Digite algo: ')
print (type(word))
print(word.isalnum())
print(word.isalpha())
print(word.isdecimal())
print(word.isdigit())
print(word.isidentifier())
print(word.islower())
print(word.isnumeric())
print(word.isprintable())
